apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqd.fullname" . }}
  labels:
    {{- include "nsqd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 4150
      targetPort: tcp
      name: tcp
    - port: {{ .Values.service.port }}
      targetPort: http
      name: http
  clusterIP: None
  selector:
    {{- include "nsqd.selectorLabels" . | nindent 4 }}
