apiVersion: v1
kind: Service
metadata:
  name: {{ include "nsqadmin.fullname" . }}
  labels:
    {{- include "nsqadmin.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4170
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    {{- include "nsqadmin.selectorLabels" . | nindent 4 }}
